{{- if and .Values.mongodb.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservices-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  database-user: {{ required "mongodb.auth.username is required when existingSecret is empty" .Values.mongodb.auth.username | quote }}
  database-password: {{ required "mongodb.auth.password is required when existingSecret is empty" .Values.mongodb.auth.password | quote }}
{{- end }}
