apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: microservices

spec:
  # Empty selector means every Pod in this namespace.
  podSelector: {}

  policyTypes:
    - Ingress
